# Generated by Django 4.0.6 on 2022-08-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_remove_currency_symbol_currency_symbol_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_description',
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('P', 'Personal Account'), ('B', 'Business Account')], max_length=20),
        ),
    ]
