# Generated by Django 4.0.6 on 2022-08-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_remove_transaction_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('P', 'Debit Card'), ('B', 'Credit Card')], max_length=20),
        ),
    ]
